blank_issues_enabled: false
contact_links:
  - name: Troubleshooting
    url: https://github.com/newrelic/newrelic-python-agent/blob/main/README.rst#support
    about: checkout the README for troubleshooting directions
